DELETE http://localhost:3003/api/blogs/6865b0b8a8d6b4f8d6c12345
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1vbmEiLCJpZCI6IjZhNDY1Y2RiODU0NDQ1NmQ3NjAwYjdlNiIsImlhdCI6MTc4Mjk5NzU3Nn0.CzTMFo07Waq-TAJJbVWaXUA3mL2Q49NFwMGrnSFfz1A